# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Gfbmdl

import flatbuffers

class BoneRigidData(object):
    __slots__ = ['_tab']

    # BoneRigidData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoneRigidData
    def Unknown1(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateBoneRigidData(builder, Unknown1):
    builder.Prep(1, 1)
    builder.PrependInt8(Unknown1)
    return builder.Offset()
