# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Gfbmdl

class BufferFormat(object):
    Float = 0
    HalfFloat = 1
    Byte = 3
    Short = 5
    BytesAsFloat = 8

