# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Gfbmdl

import flatbuffers

class ColorRGB32(object):
    __slots__ = ['_tab']

    # ColorRGB32
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ColorRGB32
    def R(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ColorRGB32
    def G(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # ColorRGB32
    def B(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateColorRGB32(builder, R, G, B):
    builder.Prep(4, 12)
    builder.PrependFloat32(B)
    builder.PrependFloat32(G)
    builder.PrependFloat32(R)
    return builder.Offset()
