# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Gfbmdl

import flatbuffers

class MatColor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMatColor(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MatColor()
        x.Init(buf, n + offset)
        return x

    # MatColor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MatColor
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MatColor
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .ColorRGB32 import ColorRGB32
            obj = ColorRGB32()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MatColorStart(builder): builder.StartObject(2)
def MatColorAddName(builder, Name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(Name), 0)
def MatColorAddColor(builder, Color): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Color), 0)
def MatColorEnd(builder): return builder.EndObject()
