# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Gfbmdl

import flatbuffers

class MeshPolygon(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMeshPolygon(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MeshPolygon()
        x.Init(buf, n + offset)
        return x

    # MeshPolygon
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MeshPolygon
    def MaterialIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MeshPolygon
    def Faces(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # MeshPolygon
    def FacesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # MeshPolygon
    def FacesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def MeshPolygonStart(builder): builder.StartObject(2)
def MeshPolygonAddMaterialIndex(builder, MaterialIndex): builder.PrependUint32Slot(0, MaterialIndex, 0)
def MeshPolygonAddFaces(builder, Faces): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Faces), 0)
def MeshPolygonStartFacesVector(builder, numElems): return builder.StartVector(2, numElems, 2)
def MeshPolygonEnd(builder): return builder.EndObject()
