# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Gfbmdl

import flatbuffers

class UnknownEmpty(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUnknownEmpty(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnknownEmpty()
        x.Init(buf, n + offset)
        return x

    # UnknownEmpty
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnknownEmpty
    def Unk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def UnknownEmptyStart(builder): builder.StartObject(1)
def UnknownEmptyAddUnk(builder, unk): builder.PrependUint32Slot(0, unk, 0)
def UnknownEmptyEnd(builder): return builder.EndObject()
