# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Gfbmdl

class VertexType(object):
    Position = 0
    Normal = 1
    Binormal = 2
    UV1 = 3
    UV2 = 4
    UV3 = 5
    UV4 = 6
    Color1 = 7
    Color2 = 8
    Color3 = 9
    Color4 = 10
    BoneID = 11
    BoneWeight = 12

